# Generated by Django 4.0.2 on 2022-02-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoge', '0004_alter_staff_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=255, null=True, verbose_name='やること')),
                ('set_date', models.DateTimeField(blank=True, null=True, verbose_name='いつまでに')),
            ],
        ),
    ]
