# Generated by Django 4.0.2 on 2022-02-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoge', '0005_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='set_date',
            field=models.DateField(blank=True, null=True, verbose_name='いつまでに'),
        ),
    ]
